blank_issues_enabled: false
contact_links:
  - name: 讨论区
    url: https://github.com/daizihan233/HanBot/discussions/
    about: 可以来这里水贴，或者提问一些的问题，当然这些问题可以没有任何意义，比如说闲聊
  - name: Discussions速成
    url: https://github.com/daizihan233/HanBot/discussions/18
    about: 如果不会用讨论区请看这里！
  - name: 祖安功能相关公告
    url: https://github.com/daizihan233/HanBot/discussions/20
    about: 最近祖安功能有调整，关于祖安功能的问题先别急着问，先看看这里吧！
  - name: 所有公告
    url: https://github.com/daizihan233/HanBot/discussions/categories/announcements
    about: 所有的公告都在这里~